version: "3.5"
networks:
  development:
  test:
volumes:
  db_data:
  gem_cache:
  shared_data:
services:
  mystore_redis:
    image: redis:4.0-alpine
    container_name: mystore_redis
    command: redis-server
    networks:
      - development
      - test
    ports:
      - "6379:6379"
    volumes:
      - shared_data:/var/shared/redis

  mystore_db:
    image: postgres:12.5-alpine
    container_name: mystore_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      - development
      - test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  #ror api
  mystore_api:
    build:
      context: backend
    container_name: mystore_api
    volumes:
      - ./backend:/var/api
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - development
    ports:
      - 3001:3000
    stdin_open: true
    tty: true
    env_file: ./backend/.env.development
    entrypoint: dev-entrypoint.sh
    command: ["rails", "server", "-p", "3000", "-b", "0.0.0.0"]
    environment:
      RAILS_ENV: development
    depends_on:
      - mystore_db
      - mystore_redis
  #ror api test
  mystore_test:
    image: mystore_mystore_api
    container_name: mystore_test
    volumes:
      - ./backend:/var/api
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - test
    ports:
      - 3002:3000
    stdin_open: true
    tty: true
    env_file: ./backend/.env.test
    entrypoint: test-entrypoint.sh
    command: ["rails", "-v"]
    environment:
      RAILS_ENV: test
    depends_on:
      - mystore_db
      - mystore_redis
